# Oracle settings
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: gcdevelop
    password: gcdevelop
    driver-class-name: oracle.jdbc.driver.OracleDriver

    # HikariCP settings
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  # enable SQL logging
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
#    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.overit.dataversioning: debug