-- ALTER SESSION SET CURRENT_SCHEMA = gcdevelop;

CREATE SEQUENCE GCDEVELOP.SXPRJAUSER INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

CREATE TABLE GCDEVELOP.XPRJAUSER
(
    XPRJAUSEID       NUMBER(10, 0) NOT NULL,
    XPRJAUSEUSERNAME VARCHAR2(64)  NOT NULL,
    XPRJAUSEPASSWORD VARCHAR2(64)  NOT NULL,
    XPRJAUSENAME     VARCHAR2(100) NOT NULL,
    XPRJAUSESURNAME  VARCHAR2(100) NOT NULL,
    XPRJAUSEVERSION  NUMBER(10, 0) NOT NULL,
    DATASTAMP        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LOGIN            NUMBER(10, 0),
    ACTION           NUMBER(10, 0),
    CONSTRAINT XPRJAUSER_PK PRIMARY KEY (XPRJAUSEID)
);

CREATE UNIQUE INDEX XPRJAUSE01 ON GCDEVELOP.XPRJAUSER (XPRJAUSEUSERNAME);
